pages:
  - /index.md
  - /tutorial1.md
  - /proj.md
  - /contents.md
  - /contents_props.md
  - /indexobj.md
  - /feed.md
  - /config.md
  - /theme.md
  - /template.md
  - /objects.md
  - /samples.md
