version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
        environment:
          PIPENV_VENV_IN_PROJECT: 1
    steps:
      - checkout
      - run: # install and activate virtual environment with pip
          command: |
            pip install pipenv
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            pipenv install
      - save_cache: # special step to save dependency cache
          key: deps1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
      - run: git config --global user.email "auto@example.com"
      - run: git config --global user.name "auto circleci"
      - run: pipenv run ./build_all.sh
      - run: pipenv run ./deploy_ghp.sh
