version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
        environment:
          PIPENV_VENV_IN_PROJECT: 1
    steps:
      - checkout
      - run: # install and activate virtual environment
          command: |
            python3 -m venv .venv
#      - restore_cache:
#          key: deps1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            pip install -r requirements.txt
#      - save_cache: # special step to save dependency cache
#          key: deps1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
#          paths:
#            - ".venv"
      - run: git config --global user.email "auto@example.com"
      - run: git config --global user.name "auto circleci"
      - run: PATH=./.venv/bin:$PATH ./deploy_ghp.sh
