lang: ja
site_title: Miyadaiku
site_url: https://miyadaiku.github.io

themes:
  - miyadaiku.themes.pygments
  - miyadaiku_theme_bootstrap4
  - miyadaiku_theme_fontawesome
  
lang_pages:
  ja: '/ja/index.rst'
  en: '/en/index.rst'

lang_default: '/en/index.rst'


