# Miyadaiku config file

# Base URL of the site
site_url: https://www.example.com

# Title of the site
site_title: Sample newblog

# Default language code
lang: ja

# Default charset
charset: utf-8

# Default timezone
timezone: Asia/Tokyo

copyright: Copyright  © 2020 Miyadauku

favicon: /static/logo.png

# Default page description
og_description: Sample new blog site

# Default page image file
og_image: /static/logo.png

# site logo
site_logo: /static/logo.png

# List of site theme
themes:
  - miyadaiku_theme_newblog

